edn:
  kafka:
    #broker-address: enps-nal-dev1.tlab.equinix.com:9092,enps-nal-dev1.tlab.equinix.com:9093,enps-nal-dev1.tlab.equinix.com:9094
    broker-address: sv3lxgna-kafka.lab.equinix.com:9092
    consumer-group: edn-network-data-transformer
    concurrency: 1
    topic:
      gnmi-raw-data:
        topic-name: gnmic-telemetry
        partitions: 1
        replicas: 1
      normalized-data:
        topic-name: edn-normalized-telemetry-data
        partitions: 1
        replicas: 1


